### ISSUE TITLE
admin_enqueue_scripts() calls get_field_data() on every admin page view

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-analytics#126]
I'm seeing a remote request calls in admin pages like themes.php to ES when I don't think they should be. Per https://github.com/humanmade/aws-analytics/blob/master/inc/audiences/namespace.php#L368, `get_field_data()` is called on every admin page load, this is cached for an hour (though in my case I was seeing it hit time and time again, as ES was timing out after 5 seconds.

Per @roborourke, I don't think this is intended behavior.

**Comment by roborourke** [comment]
This has been removed now as of #173
