### ISSUE TITLE
Audience Preview shows even if no personalised content is on the page

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/aws-analytics#139]
Not sure this is the right place to log this. But we can always move this issue. 

I am referring to the main Altis demo site page which currently displays all the posts that have been created to test. Now, I did not find any post on this page that was using a personalized content and hence an audience. Still, if you see the audience preview, it shows Chrome/ Safari and Apple users checked in case of viewing it on Chrome or Safari as the case may be. 

This might create confusion when trying to understand which page is really using personalization.    

![image](https://user-images.githubusercontent.com/55112796/104643694-c40b3600-567a-11eb-9516-97eded6a29a9.png)
![image](https://user-images.githubusercontent.com/55112796/104645293-df774080-567c-11eb-81ea-91a693e66cfb.png)

You would notice the content of this page is exactly the same yet, it shows different audience selection in the preview which gives an impression that some content on this page is personalized to that browser.   

## Requirement
As a User, I would like to understand whether a page is using personalized content just from the preview else its confusing to understand just by looking at the final pages as to which pages are using personalized content. Also, the second part of this is that if a page is not using any personalized content, then the audience preview should not display any 'checked' audiences.

## Acceptance criteria
- [ ] ....

**Comment by roborourke** [comment]
On this one there may potentially other custom code interacting with audiences. I'd say it's a low priority thing, if we even change this at all.

I had considered a different approach by exposing some UI to change the variation being viewed inline with each XB instead but this was a more straightforward blanket approach to previewing for the time being.

**Comment by PriyaBhatia0210** [comment]
Yes, low priority for sure. 
Will revisit later. Keeping in backlog though.

**Comment by rmccue** [comment]
Let's keep this how it is for now at least.
