### ISSUE TITLE
Add privacy policy page content suggestion

### ISSUE THREAD

**Issue by roborourke** [humanmade/aws-analytics#15]
WordPress's privacy policy page provides some tools we can integrate with to ensure users of this plugin are meeting requirements.

Docs here: https://developer.wordpress.org/plugins/privacy/suggesting-text-for-the-site-privacy-policy/

**Comment by roborourke** [comment]
Important note re. GDPR, need to check that the data gathered by default isn't personally identifiable. It shouldn't be unless you're logged in but should double check.

**Comment by roborourke** [comment]
We don't collect IP addresses but the data can be used to build up a picture of a single visitors path through the website so this should be made clear.

**Comment by rmccue** [comment]
This has been open for a long time and doesn't seem like a priority currently, closing.
