### ISSUE TITLE
Special characters (like ampersands) do not render correctly in analytics page

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/aws-analytics#192]
![Screen Shot 2021-04-02 at 2 08 17 PM](https://user-images.githubusercontent.com/991511/113450393-0d873980-93bd-11eb-9f2e-95f2f9963919.png)

Steps to reproduce:
1. Create a new personalization block
2. Add a title that includes an ampersand (e.g. "This & That")
3. Save the post
4. Navigate to the Experience Insights page
5. Click on the name of the block
6. See the error in the single analytics page

**Comment by roborourke** [comment]
Classic
