### ISSUE TITLE
Infinity% still displays when there's no data to calculate conversion rate

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/aws-analytics#193]
May have reverted with a bad merge?

![Screen Shot 2021-04-02 at 2 08 39 PM](https://user-images.githubusercontent.com/991511/113450551-68209580-93bd-11eb-8980-58113743f319.png)

Steps to reproduce:
1. Add a new personalization block to a post with multiple audiences
2. Save the post
3. Navigate to the Experience Analytics page
4. Click on the block
5. See error

**Comment by roborourke** [comment]
Not seeing this. Maybe need to do an `npm run build` on your local? Was this on platform-test? Not seeing it there either.

**Comment by jazzsequence** [comment]
I wasn't seeing this last time it came up either. I will re-test. I've been switching back and forth between two local environments to confirm issues and to try to identify differences, so I'll get it figured out. 👍

**Comment by jazzsequence** [comment]
Not seeing this anymore either. May have been running on an old build. Closing.
