### ISSUE TITLE
Editors cannot view experience insights

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/aws-analytics#194]
As an editor, I cannot view the XB analytics at all. The button does not appear for me on the Edit Post page and clicking the link from the Experience Insights page gives me a "Sorry, you are not allowed to access this page." error.

![Screen Shot 2021-04-02 at 3 03 57 PM](https://user-images.githubusercontent.com/991511/113454133-c00eca80-93c4-11eb-92c0-664073a2febd.png)

![2021-04-02 at 3 03 PM](https://user-images.githubusercontent.com/991511/113454140-c4d37e80-93c4-11eb-997d-935deb882210.gif)

**Comment by roborourke** [comment]
Can you check this again? Just went through the motions on platform-test and I don't get the permissions errors. Same on local. Might have been related to the other problems that came up with CloudFront.

**Comment by jazzsequence** [comment]
Not able to reproduce now. Closing.
