### ISSUE TITLE
Cloned posts with XBs do not create new XB posts

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/aws-analytics#195]
When cloning a post that has XBs, the cloned post contains the same XB. This overwrites the _existing_ XB `post` so that only one of the two XBs will appear in the Experience Analytics page depending on which was last updated.

The attached gif shows two posts, one cloned from the other, and the Experience Analytics page. When the cloned post is updated, the XB in _that_ post overrides the XB from the original post.

This is likely because the XB id is the same for both posts. A new XB id needs to be created for the cloned post.

<a href="https://imgur.com/YMpNbBe">Screencap of issue</a>

**Comment by roborourke** [comment]
The post cloner plugin doesn't have a convenient filter I can use to correct this. Will need to do that first.
