### ISSUE TITLE
Athena support for querying S3 data lake

### ISSUE THREAD

**Issue by roborourke** [humanmade/aws-analytics#20]
The analytics data is sent from Pinpoint through to a Kinesis Data Stream where it is backed up to S3 and then delivered to Elastic.

AWS Athena allows for querying the data stored in S3 and providing a mechanism for making those queries in this plugin could have good use cases:

- Privacy: data export / deletion, not just from elastic
- Historical data queries
- Alternative query language to Elastic, may be better for some types of query

Caveats:

- Quite high costs per query when lots of data gathered, would need to rate limit or not do any queries without a direct user action

Would be interested in your thoughts here @faishal & @Japh

**Comment by rmccue** [comment]
Athena is super expensive and I think there are better ways to query this data, so closing out.
