### ISSUE TITLE
Store bot status in attributes

### ISSUE THREAD

**Issue by rmccue** [humanmade/aws-analytics#217]
We currently store UA data in analytics, but don't separate out bot traffic. For example, the user agent for Googlebot is ` Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z‡ Safari/537.36` which will be identified as Chrome.

This means we later can't exclude bot traffic from reports.

Related: https://github.com/faisalman/ua-parser-js/issues/227

**Comment by roborourke** [comment]
Bots are now excluded by default as they're not really useful for what we're doing with the data or useful to our customers without more advanced capabilities built on top.

#281 added the ability to not exclude bots as well, and in such cases we add `attributes.isBot` to the event data so we can query for its existence.
