### ISSUE TITLE
Apply months_dropdown_results filter for the specific content type

### ISSUE THREAD

**Issue by skswong8** [humanmade/aws-analytics#227]
### Issue
There's an issue where `add_filter( 'months_dropdown_results', '__return_empty_array' );` is affecting other content types such as Posts and Pages in removing the `All dates` filter

### Steps to replicate
- Visit the Posts and Pages listing page in the dashboard and you will see the `All dates` filter is missing

### Expected behaviour
- `All dates` filter should be present between Bulk actions and All Categories filters for all other content types

![image](https://user-images.githubusercontent.com/3299318/125625703-28af9391-e784-4dae-b2c1-911ea432f982.png)

**Comment by skswong8** [comment]
I've created a PR which captures the changes https://github.com/humanmade/aws-analytics/pull/228

**Comment by roborourke** [comment]
Fixed by #228 and released in version 4.0.7. Altis tracks the patch version of this plugin so running `composer update` will get the fixed version.

**Comment by skswong8** [comment]
Thanks @roborourke!
