### ISSUE TITLE
3rd party sorting labels overlapping elements

### ISSUE THREAD

**Issue by skswong8** [humanmade/aws-analytics#232]
I don't imagine the aws-analytics plugin providing support for functionality provided by 3rd party plugins but thought I'd raise awareness if any others encounter the same issue

As you can see from the screenshot below, the 'Sort by Order' label provided by [Simple Page Ordering plugin](https://github.com/10up/simple-page-ordering/) is overlapping some of the date filters
![125733429-a0c834a3-1cef-4e1e-8693-8c39491f5ae1](https://user-images.githubusercontent.com/3299318/127075698-4574130a-1425-4994-9265-b1c5c094ff7f.png)

### Simple Page Ordering solution ✅ 
```
add_filter( 'simple_page_ordering_is_sortable', __NAMESPACE__ . '\\remove_sortable_for_xb', 10, 2 );
function remove_sortable_for_xb( bool $sortable, string $post_type ) : bool {
	if ( $post_type === 'xb' ) {
		return false;
	}
	return $sortable;
}
```

**Comment by roborourke** [comment]
Might be a lot of cases like this. Do you know what logic that plugin uses to decide whether to add its UI there or not? Maybe we should change that page to an embedded react component like the audiences UI.

**Comment by skswong8** [comment]
I think generally it's applied if the post type is hierarchical then by default it will apply this functionality, or by applying `page-attributes` when defining the post type support
See: https://github.com/10up/simple-page-ordering#can-i-make-my-custom-post-type-take-advantage-of-this-plug-in

The action gets called here: https://github.com/10up/simple-page-ordering/blob/develop/simple-page-ordering.php#L47
The two conditions checked here: https://github.com/10up/simple-page-ordering/blob/develop/simple-page-ordering.php#L67

**Comment by rmccue** [comment]
Marking as a won't fix; this is a problem with an external plugin, so integration steps are needed.
