### ISSUE TITLE
A/B Test preview from a widget

### ISSUE THREAD

**Issue by robindevitt** [humanmade/aws-analytics#298]
#### Issue
Currently you can't successfully preview an A/B Test block from within the widget area or customizer.

[Link to Slack thread](https://hmn.slack.com/archives/C5WSNGC9F/p1639404206213400) relating to the issue.

#### Accepted Criteria
- Successfully view an A/B Test Block from with the widget area
- Successfully view an A/B Test Block and edit the content within the customizer

**Comment by roborourke** [comment]
Fixed by #306
