### ISSUE TITLE
Preview link as a component

### ISSUE THREAD

**Issue by robindevitt** [humanmade/aws-analytics#299]
Currently we are reusing code to generate the preview link. This issue will create the preview link as a shared component that be reused.

[Initial suggestion for the change](https://github.com/humanmade/aws-analytics/pull/295#discussion_r766799430)

**Comment by robindevitt** [comment]
Hey @roborourke 

On the [XB Review Widget](https://github.com/humanmade/aws-analytics/pull/300) we removed the preview links for A/B test blocks. 

Im not sure if that change impacts the need for making the preview link a component?

**Comment by roborourke** [comment]
Yeah I think we can close this one for now. We might do more as at some point we should refactor everything to use typescript.
