### ISSUE TITLE
Data export can show invalid JSON for an empty response with response code 200

### ISSUE THREAD

**Issue by roborourke** [humanmade/aws-analytics#317]
Sometimes the data export endpoint returns no results but JSON output like the following with a 200 response code:

```
[
    ,
]
```

Ways to reproduce:

- Run the export with Elasticsearch stopped
- Run the export with no entries in elasticsearch (use a DELETE request to `/analytics-*` via Kibana dev tools
- Run the export for a day in the future or a day with no data in ES

**Comment by shadyvb** [comment]
@roborourke can we add some reproduction steps here ?

**Comment by roborourke** [comment]
Added some ways to reproduce it in the original comment.

**Comment by robindevitt** [comment]
Hey @roborourke 

> Run the export with Elasticsearch stopped

How does one stop Elasticsearch?

> Run the export with no entries in elasticsearch (use a DELETE request to /analytics-* via Kibana dev tools

Is this the correct documentation for [Kibana dev tools](https://www.elastic.co/guide/en/kibana/current/devtools-kibana.html)? I came across [this](https://docs.altis-dxp.com/local-server/elasticsearch/#kibana) in the Altis Docs.

Thanks
Robin

**Comment by roborourke** [comment]
I think the images on the Altis docs are out of date but yes. There’s a link to Kibana in the Tools menu in the admin you can click, then look for Dev Tools in the left hand menu

**Comment by robindevitt** [comment]
This has been completed and merged: [Issue](https://github.com/humanmade/aws-analytics/issues/317) & [PR](https://github.com/humanmade/aws-analytics/pull/333)
