### ISSUE TITLE
Add raw data export to fetch analytics data and enable BI tool integration

### ISSUE THREAD

**Issue by roborourke** [humanmade/aws-analytics#320]
Rather than tax Elasticsearch, especially for a busy site, we should fetch export data from S3 and process it if needed.

Data in S3 is located in prefixes with the pattern `<year>/<month>/<day>/<hour>`. The files are gzipped (`.gz`) and when downloaded will be in NDJSON format, e.g. one JSON document per line in the file.

Acceptance criteria:

- [x] Background batch process that runs once per hour
- [x] NDJSON data export should iterate over files within requested date range in S3 bucket
- [x] Action to deliver batched data to external BI tool (e.g. Segment)
- [x] Retries on fetch from S3, 3 times by default with exponential back off
- [ ] Notification on processing or delivery failure to configured email address

**Comment by roborourke** [comment]
@roborourke to rewrite description for a new raw data export that returns NDJSON

**Comment by roborourke** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Altis-5c378365e15075539771e4e3/issues/humanmade/aws-analytics/320?planning-poker) with ZenHub @mikelittle @robindevitt @shadyvb

**Comment by yumito** [comment]
potentially to be included in Sprint 11.2

**Comment by shadyvb** [comment]
Can't think of a clean way to manage notifications, I'd probably defer that bit to implementations. We have the hook, they just need to hook it to an email and/or Slack, etc.

Additional reasons are:
- Defining an email in config/code isn't something we've been doing.
- Creating a UI just for this is a bit too much.
- Logs will already contain errors and successes as part of the dashboard. Fatals will also be logged in Cavalcade logs.

Also worth noting that we need to make sure we have an issue for documentation of the whole feature once it stabilizes /  is used by an actual subscriber like the planned Segment integration.
