### ISSUE TITLE
Avoid scheduling events on every request

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/aws-analytics#490]
Moved from humanmade/Cavalcade#116 per @kovshenin's [comment](https://github.com/humanmade/Cavalcade/issues/116#issuecomment-1224886054) on that ticket.

When viewing any page on a site where AWS Analytics is enabled, a number of Cavalcade queries are made and a variety of in-memory cache values are set. Per the trace in humanmade/Cavalcade#116, the origin of these queries is this function in AWS Analytics:

https://github.com/humanmade/aws-analytics/blob/aa5763c1df8e13ecb457b9db9a8deddded8ccd63/inc/namespace.php#L81-L89

Is there a reason these requests need to be made on every request, hooked to `init`, rather than in their own cron entry? While each individual request is not significant, making several needless queries and taking time to stash the data in-memory, if not necessary to render the page, makes every pageview in Altis sites slightly slower.

**Comment by missjwo** [comment]
Notes from cross-team huddle: 
- There is no plugin activation
- WordPress core does on install. 
- Maybe on Altis Migrate for Altis cloud to do it. But what about people not on Altis cloud?
- We can at least do, is change the hook on `init` to `admin-init`
  - Ajax uses admin-init. maybe something like `in-admin` or `wp-admin` or `on login`
 - the the analytic could do....

Lets do it on : 
- change the default action hook that we schedule events on to `wp-admin request`. 
- in the analytics module, remove the default hook, and schedule the events on altis migrate action instead. 

Probably should have something about this in our docs - about what if you want to do reoccurring events. // @mikelittle 
- Probably on altis-migrate hooks. 
- There is a doc on how to do schedule events.

**Comment by roborourke** [comment]
Thanks for the catch and report @kadamwhite, I've made a PR that does a few things:

- moves the events to only be scheduled when in the admin context to avoid impacting the front end
- adds a manual persistent cache check to avoid the need for querying the db each time

For Altis we may go further and make these schedules added when running `wp altis migrate`. I'll do a write up with regards to good practice here.

**Comment by roborourke** [comment]
Give it a few minutes and there will be built releases with this fix that you can update to @kadamwhite
