### ISSUE TITLE
Permit hiding or replacing "Size" column when not relevant

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/aws-analytics#501]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/442115/187239081-615dc1b6-9dae-418d-a730-50125e47dfb2.png">

Some Altis sites use audiences primarily for targeting of legally-mandated documentation and disclaimers, and may not be actively using the majority of their audiences for A/B testing. As such, showing the statistics for impressions on those audiences is of limited value on those sites, at this time.

Because the UI for the audiences is rendered in JavaScript, with no sort of slot or fill available, the only way we can hide this column as requested by the client is to use CSS. It would be more flexible to have some kind of filter available to suppress or replace the `<Estimate>` component.

**Comment by rmccue** [comment]
This isn't really what the feature is designed for, and it's at-odds with the goals of the feature, so we're not planning on making this configurable, sorry!
