### ISSUE TITLE
HTTP (not secure) causes error due to crypto.randomUUID

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-analytics#505]
Using aws-analytics on a http site is giving me

```
Uncaught TypeError: window.crypto.randomUUID is not a function
```

According to https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID:

> Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.

Perhaps we need a polyfull or similar on http sites?

**Comment by roborourke** [comment]
I was using a library for it previously so could revert to that. I think there might be other features that don't work on HTTPS though? Do we want to support HTTP?

**Comment by roborourke** [comment]
Ahhh, thought I'd worked around this by checking if `window.crypto` exists but it's not that simple:

```js
export const uuid = placeholder => {
	if ( typeof window.crypto === 'object' ) {
		return window.crypto.randomUUID();
	}
	return placeholder
		? ( placeholder ^ ( ( Math.random() * 16 ) >> ( placeholder / 4 ) ) ).toString( 16 )
		: ( [ 1e7 ] + -1e3 + -4e3 + -8e3 + -1e11 ).replace( /[018]/g, uuid );
};
```

**Comment by joehoyle** [comment]
nice one!
