### ISSUE TITLE
Persist UTM attributes and referrer

### ISSUE THREAD

**Issue by roborourke** [humanmade/aws-analytics#58]
**User Story:**
As a marketer, I want to personalize content based on the initial referrer to the website so that I can understand the conversion of my different marketing campaigns (social / email /etc.)

**Requirement:**
All the UTM parameters and the referrer selection should list the audience that came from the very first campaign they were referred by. Basically, the initial referrer should be sticky. Eg: A website visitor who visited through a social media campaign should always be listed under the UTM attribute = social.    

**Acceptance Criteria:**
Given: A user visits the site from a campaign or clicks through a site
When: They visit another page with personalized content 
Then: They should see the personalized content based on the initial referrer they came from

**Comment by roborourke** [comment]
cc @Kenshino - will try and get this added asap

**Comment by rmccue** [comment]
We should add referer to this list of parameters to persist too.

**Comment by roborourke** [comment]
Yeah, captured in an issue on the Altis analytics repo. Fairly quick update to do
